### ISSUE TITLE
Feature request: print blank line between runs with -b

### ISSUE THREAD

**Issue by dboehmer** [eradman/entr#135]
I often use entr to run scripts that write a few lines to the terminal. In order to compare output from multiple runs I can’t use the `-c` for clearing the screen but it’s hard to distinguish the runs.

I’d love to see an option `-b` that prints a single blank line between runs.

This can be improvised with `entr -s "echo; my_command"` but this also prints a blank line before the first run.

**Comment by eradman** [comment]
`-b` is likely not flexible enough for most people. It is very common to chain two commands to separate executions visually, but a great deal of variation in what people do:

1. status message indicating execution started
2. dynamic status (such as running the `date` command)
3. ANSI color-coded status message after execution
4. ANSI color-coded status message based on the exit code
5. status message or delimiter after execution

So far I have not been able to see a solution that solves more than two of these at a time, which is why it is left up to each person to add their own `printf` statements before or after the command.

**Comment by eradman** [comment]
Closing in favor of #137. It's probably time to think about how to configure before/after status messages.
