### ISSUE TITLE
support NUL-separated input

### ISSUE THREAD

**Issue by amckinlay** [eradman/entr#18]
It would be nice if entr accepted filenames containing newlines. Then, I could safely pass a list of files to entr separated by NULs: `zsh> print -Nnr - src/* | entr ...`. Perhaps this could be toggled with the addition of a `-0` flag?

**Comment by eradman** [comment]
Writing filenames containing newlines seems like a bad idea. Why would this occur? Lots of programs can't handle this condition.

I spent a little time looking into the implementation. At a glance it appears to be a problem because common libc functions like fgets(3) stop at newlines, and don't provide a method of determining the real string length.

**Comment by amckinlay** [comment]
Perhaps the `scanf` family of functions with the specifier `"%[^\0]"` can help?

**Comment by amckinlay** [comment]
`find`'s `-print0` and `xargs`'s `-0` seem to justify this feature. Pathnames cannot have NUL characters in them. You're right, for `entr`'s use cases it does seem encountering a non-human readable filename on standard input is doubtful. Is `entr` not meant to be scripted? Maybe this feature is useless.

**Comment by eradman** [comment]
My guess is that `find` and `xargs` support `-0` because _some_ core utilities need to be able to deal with this condition. This feature was requested once before, but without a compelling use case I'm going leave this as a corner case that is not supported.
