### ISSUE TITLE
On watching symlinks

### ISSUE THREAD

**Issue by clacke** [eradman/entr#30]
As asked in clibs/entr#5, would it be possible to watch symlinks? Or is there a limitation to how `inotify` works that stops this?

**Comment by eradman** [comment]
I tried testing this, and this does appear to be a limitation for inotify_add_watch(2). Unlike open(2), there is no`O_NOFOLLOW` option. Even if this were possible, I think this would cause a lot of unexpected behaviors.

**Comment by toonn** [comment]
I stumbled across this in the inotify(7) man page:

> The following further bits can be specified in mask when calling inotify_add_watch(2):
>
>     IN_DONT_FOLLOW (since Linux 2.6.15)
>       Don't dereference pathname if it is a symbolic link.

I think this means that at least in theory this would be possible now.

Looked into it because in the Nix ecosystem, `result` symlinks are common when working with `nix-build` and it could be useful to rerun a command whenever the target of that symlink changes.
