### ISSUE TITLE
entr process dies when a watched file is deleted (repost)

### ISSUE THREAD

**Issue by tony** [eradman/entr#48]
This was originally asked by @basti1302 in 2016 : https://github.com/clibs/entr/issues/4#issue-149373079

It was apparently forwarded to the bit bucket tracker, but the issue is now a 404: https://bitbucket.org/eradman/entr/issues/40/entr-process-stops-when-a-watched-file-is

I'm posting this since it's been a couple years and I want to be sure Google has some decisive answers for users that encounter this (Hopefully!)

Here is the example verbatim, that still happens with `entr 4.4`:

```sh
> touch a
> touch b
> touch c
> ls a b c  | entr echo Yo
```

> Now, in another shell, each `touch a`, `touch b` or `touch c` will produce a Yo, as expected, but a `rm` a will cause the entr process to stop with the following error message:

```
> rm b
entr: cannot open `b': No such file or directory
```

Does `entr(1)` have a way to handle cleaned / removed / unlinked files?  Is there a workaround?

(Thank you very much for this application!)

**Comment by eradman** [comment]
The bitbucket tracker is gone because Atlassian decided to delete all of their Mercurial repositories! Fine, it was time to move to git anyway.

`entr` reacts to deleted files by attempting to reopen them. This happens frequently since write/rename/unlink is the only way to ensure an atomic write, and it's what most file in most editors.

The man page suggests the following when using the `-d` flag, and you can use the same method to handle the condition where a file is removed

```
while true; do
    ls src/*.rb | entr -d make
done
```

I don't think there is any other reasonable behavior; a warning is easily missed. 

Writing a shell loop explicitly is annoying, but allows the user to run commands which can raise an alert, re-scan a directory, or even abort if certain criteria are not met.
