### ISSUE TITLE
Use of /_ argument

### ISSUE THREAD

**Issue by andrewmgibb** [eradman/entr#67]
I am using entr to monitor a folder of XML files. I would like to use it with a tool that takes the file that has been modified and then converts it from XML to Markdown. The tool (the DITA-OT https://www.dita-ot.org/dev/topics/build-using-dita-command.html) requires a file path under an input command:

--input="file/path"

I am trying to use the /_ placeholder to capture the filepath of the file that has been changed but not having any success. How can I 'extract' the file path (into a variable or otherwise) which I can use in the 'utility' part of the entr command? Something like below, I have tried a few combinations without any success.

ls * | entr -p dita --input="**/_**" --format=markdown_github --output="./output/path" -v

I appreciate any help you can offer. Thank you.

**Comment by eradman** [comment]
The `/`_ shortcut for entr was intended as a means of saving typing in the case where you are monitoring one file

    echo schema.sql | psql -f /_

For any other use it incorrect because the operating system my consolidate events for files that were changed in close succession, but entr only prints one filename.

Over time I have been asked to extend and enhance the capabilities of the `/_` shortcut; this is usually to in an effort to

1. emulate rsync(1) (send only files that changed)
2. emulate make(1) (build only files that changed)

The philosophy I usually reply with is: entr(1) will detect if something changed in your tree, but another tools needs to handle building source or copying files.

In your case I would write a Makefile or something similar

```make
.SUFFIXES: .xml .markdown

SOURCES != ls input/*.xml | awk 'sub("\.xml$$", ".markdown")'

.xml.markdown:
    dita --input=$< --format=markdown_github --output=$@ -v

all: ${SOURCES}
```

Then monitor using

```
while sleep 0.1; do
    ls *.xml | entr -d make
done
```

make(1) uses the modification times of files to determine what needs to be updated. You can also do this comparison in shell, which may be more adaptable to your directory structure

```sh
#!/bin/sh

for input in $(ls input/*.xml); do
  output="output/$(basename $input .xml).markdown"
  [[ $input -nt $output ]] && {
      (set -x; dita --input=$input --format=markdown_github --output=$output -v)
  }
done

```

**Comment by eradman** [comment]
@andrewmgibb this is a somewhat common and very good question. I have edited the answer above and put it on the project home page:

http://eradman.com/entrproject/

**Comment by andrewmgibb** [comment]
@eradman Thanks for your help, much appreciated!

**Comment by dufferzafar** [comment]
@eradman You mentioned `send only files that changed`, how can that be achieved using rsync / scp ?

I currently have something like this (using inotifywait) 

```bash
while inotifywait -r -e modify /source/directory; do
    rsync -av --exclude build  /source/directory remote.host:/target/directory
done
```

But this is ignoring the information of the file that changed. Perhaps using entr + scp will be a bit faster?

**Comment by eradman** [comment]
@dufferzafar the equivalent for entr would be

```sh
while sleep 1; do
  find sync_user | entr -d rsync -av /source/directory remote.host:/target/directory
done
```

The `while` loop will be used every time a file is added or removed from a directory, and any changes to a file under `/source/directory` will be monitor for changes.
